---
title: "MVA5"
author: "Sai Madhuri"
date: "2024-03-08"
output: html_document
---

```{r}

autompg <- read.csv("/Users/user/Downloads/auto-mpg.csv")
str(autompg)
autompg$horsepower <- as.integer(autompg$horsepower)
cleaned_auto <- na.omit(autompg)
str(autompg)

```
```{r}
#load necessary libraries
library(magrittr)
library(NbClust)
library(cluster)
library(factoextra)

```



```{r}

#Hierarchical Clustering- Dendrogram
auto_featured <- cleaned_auto[, c("mpg","horsepower", "weight", "acceleration")]
auto_clust <- auto_featured[1:10,]
auto_mpg_scaled <- scale(auto_clust)
dist_matrix <- dist(auto_mpg_scaled)

#Clustering Single
hc <- hclust(dist_matrix,method = "single")
plot(hc, hang = -1, cex = 0.6, main = "Dendrogram for Hierarchical Clustering")

```





```{r}
#Default Clustering

hc <- hclust(dist_matrix)
plot(hc, hang = -1, cex = 0.6, main = "Dendrogram for Hierarchical Clustering")

```







```{r}
#Average Clustering

hc <- hclust(dist_matrix,method = "average")
plot(hc, hang = -1, cex = 0.6, main = "Dendrogram for Hierarchical Clustering")

```

#By observing the above dendrogram's k=3 clusters will be sufficient.





```{r}

num_clusters <- 3
clusters <- cutree(hc, k = num_clusters)

# Membership for each cluster
table(clusters)

# Visualize cluster and membership using first two Principal Components
pca_result <- prcomp(auto_clust,scale=TRUE)
fviz_cluster(list(data = pca_result$x[,1:2], cluster = clusters))


```


```{r}
#Non-Hierarchical Clustering
num_clusters <- 3 
kmeans_model <- kmeans(auto_clust, centers = num_clusters)

# Membership for each cluster
table(kmeans_model$cluster)

```

```{r}
# Visualize cluster and membership using first two Principal Components
fviz_cluster(list(data = pca_result$x[, 1:2], cluster = kmeans_model$cluster))
```


```{r}

```